/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n9.0.2-3-ga5923073bf-20260922"
#endif /* AVUTIL_FFVERSION_H */
